# Generated by Django 5.0.6 on 2024-07-09 16:04

import organization.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=organization.generate.generate_user_id, max_length=255, unique=True),
        ),
    ]
